### ISSUE TITLE
bibdata refactor changes

### ISSUE THREAD

**Issue by opoudjis** [metanorma/relaton-gb#22]
The following changes impact this gem, as elements moved to bibdata/ext from bibitem. All elements specific to GB must be populated in bibdata/ext; please ask me if there are any changes not covered in the following.

The grammar of ext (which inherits from ISO) is:

````
BibDataExtensionType =
    doctype?, gbcommittee*, ics*, structuredidentifier, gbtype, gbccs+, gbplannumber?

gbccs = element ccs {
  element code {text},
  element text {text}?
}   

gbplannumber = element plannumber { text }
    
gbcommittee =
  element gbcommittee {
    attribute type { ( "technical" | "provisional" | "drafting" ) },
    text
}   

gbtype =
  element gbtype {
    gbscope, gbprefix, gbmandate, gbtopic
}

DocumentType = "standard" | "recommendation"
````

* The type of standard, e.g. "recommendation", is no longer set in `bibitem/@type`. It is now set in `bibdata/ext/doctype`

* `title-main` is replaced with `title[@type = 'title-main']`. The `lang` attribute is retained.

* `title-intro` is replaced with `title[@type = 'title-intro']`. The `lang` attribute is retained.

* `title-part` is replaced with `title[@type = 'title-part']`. The `lang` attribute is retained.

* A `title[@type = 'main']` shall be added, consisting of title-main, title-intro, title-part, joined by space-endash-space. The `lang` attribute is retained.

* `gbcommittee` moves to `bibdata/ext`.

* `ics` moves to `bibdata/ext`.

* The structured GB identifier, using project-number and part-number attributes, is moved from bibitem/docidentifier to bibdata/ext/structuredidentifier. In bibitem/docidentifier, the ISO identifier given should be the identifier as it appears on the site, with the part numbers incorporated; e.g. `<docidentifier type="ISO">ISO 631-1</docidentifier>` vs `<structuredidentifier><project-number part="1">ISO 631</project-number></structuredidentifier>`

* `gbtype`, `gbccs`, and `gbplannumber` all move to `bibdata/ext`.

**Comment by andrew2net** [comment]
@ronaldtser what is the essence of the `gbplannumber` element? Where we can scrape it?

**Comment by andrew2net** [comment]
@ronaldtse since we don't have a text element `/bibitem/status/status` anymore, where can we scrape `stage` and `substage`?
New grammar for status element:
```
status =
  element status {
     ( stage, substage?, iteration? )
}
```

**Comment by ronaldtse** [comment]
`gbplannumber` is the project number for GB. Somehow the gb688.cn website isn't working for me...?

**Comment by andrew2net** [comment]
@opoudjis I think we don't have `title-intro` and `title-path` for GB docs
> - title-intro is replaced with title[@type = 'title-intro']. The lang attribute is retained.
> - title-part is replaced with title[@type = 'title-part']. The lang attribute is retained.
> - title-part is replaced with title[@type = 'title-part']. The lang attribute is retained.
> - A title[@type = 'main'] shall be added, consisting of title-main, title-intro, title-part, joined by space-endash-space. The lang attribute is retained.

If a document has only `title-main` do we need to add a `main` type title?

**Comment by opoudjis** [comment]
> If a document has only title-main do we need to add a main type title?

Yes. "main" is the complete title; it is logically distinct from "title-main", which is the main title component. If only "title-main" is present, "main" is identical to it.

Even if there is no title-intro and title-part (which surprises me), we should retain this behaviour, for consistency with ISO.
